### ISSUE TITLE
Importing takes too long

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#10]
### Issue description

Importing takes too long.

https://share.firefox.dev/3EEnAw7

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/a6d49575-49f9-456d-b456-5602ba66d995)

### Steps to reproduce

Import https://sketchfab.com/3d-models/facial-body-animated-party-m-0001-actorcore-aecb1b0c293a4185a91a532e635f3e6d

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/ce2bd191ba89848ae1dc4f1cedf854846eda720b

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

**Comment by bqqbarbhg** [comment]
Was probably caused by a pathological case in mikktspace as the blend shape tried to generate tangents for mesh with most vertices at zero.
