### ISSUE TITLE
Transparency may not be correctly enabled

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#17]
### Issue description

https://sketchfab.com/3d-models/sensei-4-cc86a15388ab403baff5c7a4b4d3eefc

### Steps to reproduce

1. import sensei
2. check hair
3. hair looks strange

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/bb2a6dc5-691e-49f8-be04-58afdd0ff101)

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/63aa15e4-323c-43d4-b747-bedfe1a164dd)

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/6e4a7a3e5cfb47cc9e0be3fe82bcbfc623192c7c

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

**Comment by bqqbarbhg** [comment]
This is going to be a tricky one, most FBX material definitions don't contain enough information to know if a surface is transparent or not, need to see what heuristics FBX2glTF is using internally.

**Comment by bqqbarbhg** [comment]
Looks like FBX2glTF scans the pixel data of the diffuse texture to determine if it has a non-opaque alpha channel to determine the transparency setting, we should be able to do something similar.

**Comment by fire** [comment]
WIP. I think the albdeo texture needs the alpha channel written to. Dropping it here. Feel free to take over.

Note the typo.

```c++
if (base_texture) {
	{
		bool wrap = base_texture->wrap_u == UFBX_WRAP_REPEAT && base_texture->wrap_v == UFBX_WRAP_REPEAT;
		material->set_flag(BaseMaterial3D::FLAG_USE_TEXTURE_REPEAT, wrap);

		Ref<Texture2D> albedo_texture = _get_texture(p_state, FBXTextureIndex(base_texture->file_index), TEXTURE_TYPE_GENERIC);
		material->set_texture(BaseMaterial3D::TEXTURE_ALBEDO, albedo_texture);
		if (albedo_texture.is_valid() && albedo_texture->get_image().is_valid()) {
			Image::AlphaMode alpha_mode = albedo_texture->get_image()->detect_alpha();
			if (alpha_mode == Image::ALPHA_NONE) {
				material->set_transparency(BaseMaterial3D::TRANSPARENCY_ALPHA_DEPTH_PRE_PASS);
				material->set_depth_draw_mode(BaseMaterial3D::DEPTH_DRAW_ALWAYS);
			} else if (alpha_mode == Image::ALPHA_BIT) {
				material->set_transparency(BaseMaterial3D::TRANSPARENCY_ALPHA_SCISSOR);
			}
		}
	}
	if (!fbx_material->pbr.base_color.has_value) {
		material->set_albedo(Color(1, 1, 1));
	}
	// TODO: Does not support rotation, could be inverted?
	material->set_uv1_offset(_as_vec3(base_texture->uv_transform.translation));
	Vector3 scale = _as_vec3(base_texture->uv_transform.scale);
	material->set_uv1_scale(scale);
}
```

**Comment by bqqbarbhg** [comment]
Oh wow that `detect_alpha()` API looks perfect, exactly what we need here. Thanks!

**Comment by fire** [comment]
Got stuck.

The plan is for each pixel in the transparency color texture set the albedo texture alpha and then use detect alpha to set transparency

**Comment by fire** [comment]
Work merged as of https://github.com/V-Sekai/godot-ufbx/commit/449d1cab117c32a0c0cb529375357f0a301c9c6c
