### ISSUE TITLE
The thirdparty/ufbx directory could be pruned

### ISSUE THREAD

**Issue by bqqbarbhg** [V-Sekai/godot-ufbx#19]
### Describe the proposed feature and how it helps to overcome a problem or limitation

Currently [`thirdparty/ufbx`](https://github.com/V-Sekai/godot-ufbx/tree/main/thirdparty/ufbx) contains a lot of unnecessary files for the integration like examples and tests. ufbx was designed to be embeddable by only having `ufbx.c/h` files which would add less bloat to the repository. If you want for legal reasons you can also keep the `LICENSE` file around (I should really embed it to the files as well though).

**Comment by bqqbarbhg** [comment]
And the `REDAME.md` isn't too huge either, so might be worth keeping it around. The `examples/` directory is the most offending one because it embeds yet further single file libraries like Sokol or STB, which take quite a bit of space.

**Comment by fire** [comment]
Sounds good to me, I was delaying this work until all the core features are in godot-ufbx.

**Comment by fire** [comment]
I pruned a little.

**Comment by bqqbarbhg** [comment]
Nice, that looks perfect!
