### ISSUE TITLE
Skeleton unit scaling is awkward

### ISSUE THREAD

**Issue by bqqbarbhg** [V-Sekai/godot-ufbx#20]
### Issue description

Importing small meshes exported from Maya with 1cm units causes the model to be loaded correctly as tiny, but the bounding box is massive as the `Skeleton3D` itself it not scaled, but only the root node within.

![image](https://github.com/V-Sekai/godot-ufbx/assets/3875461/473ce9a3-157a-466f-873c-eeefc99b2112)

![image](https://github.com/V-Sekai/godot-ufbx/assets/3875461/227b284a-3d39-420b-90bc-0eb1b1a16b35)

Could try to scale the `Skeleton3D` node itself, but then we need to be careful to compensate for that in animations etc. alternatively we could bake the scaling into the root node, but that had some issues as well and will require us to have an unnecessary node.

### Steps to reproduce

* Import [`ufbx/data/maya_game_sausage_7500_ascii_combined.fbx`](https://github.com/ufbx/ufbx/blob/master/data/maya_game_sausage_7500_ascii_combined.fbx)
* Observe that the bounding box is 100x larger than it should be

### Using a released version?

0b874ae

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Windows, Godot 4.2 master

**Comment by bqqbarbhg** [comment]
Turns out that there's not much that can be done here as the bounding box size is based on the _mesh_, so even if we'd fix the scale issue on bones the bounding box may be rotated. I saw that the glTF importer transforms the mesh geometry itself but that's not ideal especially for blender files, as then you end up with nodes having scale=100 and all vertices being scaled to tiny.

**Comment by fire** [comment]
The transform to identity scale to the mesh geometry itself is part of the scene importer and independent of the importers.

Also agree that this is really a rendering of Godot Engine issue and it's minor as this is used for culling (bug?) and editor debug.

**Comment by fire** [comment]
I'd probably close the issue as I have no approaches for fixing this.

**Comment by bqqbarbhg** [comment]
Yeah every approach has it's downsides, I'd consider this a Godot Engine issue as well.

**Comment by fire** [comment]
see https://github.com/godotengine/godot/pull/84451 @bqqbarbhg

**Comment by bqqbarbhg** [comment]
Yeah would need something similar for 3D probably, one solution is to just calculate maximum distance from bone to vertex and estimate the skeleton AABB by approximating bone sizes as such. Adding some fudge factor it works in practice.
