### ISSUE TITLE
Blendshape names are not correctly converted to utf8?

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#21]
### Issue description

Blendshape names are not correctly converted to utf8?

https://sketchfab.com/3d-models/klee-fbx-eb4ba3c0d92349cfaf7361e4e55604f0#download

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/8fa54f70-cafb-4d7c-b220-05b20ae1c452)

### Steps to reproduce

1. download fbx
2. scan the list of names

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/184c87aabd3346f47b528b2a4577842e90da0655

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

**Comment by bqqbarbhg** [comment]
Very interesting, ufbx does validate all strings as UTF-8, either the source file itself is garbled or something gets lost in the importer.

**Comment by bqqbarbhg** [comment]
Turns out the Godot `String()` constructor only works for ASCII, fixed in 9f83139 with `String::utf8()`

Turns out it was hiragana:

![image](https://github.com/V-Sekai/godot-ufbx/assets/3875461/edfd13e8-6033-45ee-a1bc-a7e25bcb7ed5)

**Comment by fire** [comment]
Thanks!
