### ISSUE TITLE
Remove root node

### ISSUE THREAD

**Issue by bqqbarbhg** [V-Sekai/godot-ufbx#22]
### Describe the proposed feature and how it helps to overcome a problem or limitation

If we don't end up using `UFBX_SPACE_CONVERSION_TRANSFORM_ROOT` we can get rid of the root node, as it's not a part of the FBX file proper. Just ignoring the root node and inserting everything at top-level of the scene should work fine. If we provide an option to retain/transform the root node it should at least have a better name than `Node2`.

![image](https://github.com/V-Sekai/godot-ufbx/assets/3875461/5d0afdd2-2001-4a2c-83f0-f067fadef35f)

**Comment by fire** [comment]
Can this be abstracted inside of ufbx?

**Comment by bqqbarbhg** [comment]
ufbx always has a single `root_node` but we can trivially just ignore it and use its children, as fixed in e0fed7e

**Comment by fire** [comment]
@bqqbarbhg Crash on 
<img width="1920" alt="image" src="https://github.com/V-Sekai/godot-ufbx/assets/32321/39ff7be2-f6d7-43d1-8b18-88ffed33237f">

**Comment by bqqbarbhg** [comment]
Very strange, that should have happened with the old code as well. Is this with a new model?

**Comment by fire** [comment]
@bqqbarbhg I sent you a test model on rocketchat.

**Comment by bqqbarbhg** [comment]
Thanks, I'll check it out soon. Meanwhile 0538b3c should fix the crash, but the load probably still fails in ufbx.

**Comment by fire** [comment]
A comment in the ascii fbx caused the import failure. The failure was unrelated to removing root node, but it found a crash error.
