### ISSUE TITLE
Have a fallback path for image uploads for the current directory?

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#23]
### Issue description

Is it possible to have a fallback path for the textures in the current directory or otherwise find the image?

https://sketchfab.com/3d-models/klee-fbx-eb4ba3c0d92349cfaf7361e4e55604f0

### Steps to reproduce

1. load fbx
2. missing textures

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/184c87aabd3346f47b528b2a4577842e90da0655

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

**Comment by fire** [comment]
@bqqbarbhg Any ideas?

**Comment by bqqbarbhg** [comment]
ufbx tries to resolve relative paths where possible, so this should already work in theory. I can run it through a debugger to see what's going on at some point.

**Comment by fire** [comment]
Last investigation took me to ufbx using res://image.png rather than res://somwhere/where_fbx_is/image.png

**Comment by fire** [comment]
I think this is good enough for now.
