### ISSUE TITLE
UV y coordinate flipping

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#26]
### Issue description

UVs 2-7 need UV y coordinate flipping.

### Steps to reproduce

Analytical since these are all data.

```gdshader
// NOTE: Shader automatically converted from Godot Engine 4.0.dev's StandardMaterial3D.

shader_type spatial;
render_mode unshaded;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;
uniform vec4 albedo : source_color;
uniform sampler2D texture_albedo : source_color,filter_linear_mipmap,repeat_enable;

varying vec4 custom0;
varying vec4 custom1;
varying vec4 custom2;

void vertex() {
	UV=UV;
	UV2=UV2;
	custom0 = CUSTOM0;
	custom1 = CUSTOM1;
	custom2 = CUSTOM2;
}


void fragment() {
	if (SCREEN_UV.x < 0.25) {
		ALBEDO = vec3(UV, UV2.x);
	} else if (SCREEN_UV.x < 0.5) {
		ALBEDO = abs(custom0.xyz);
		//ALBEDO = any(lessThan(abs(custom0.xyz),vec3(0.01))) ? vec3(0.0,100.0,0.0) : vec3(1.0);
	} else if (SCREEN_UV.x < 0.75) {
		ALBEDO = abs(custom1.xyz);
		//ALBEDO = any(lessThan(abs(custom1.xyz),vec3(0.01))) ? vec3(0.0,100.0,0.0) : vec3(1.0);
	} else {
		ALBEDO = abs(custom2.xyz);
		//ALBEDO = any(lessThan(abs(custom2.xyz),vec3(0.01))) ? vec3(0.0,100.0,0.0) : vec3(1.0);
	}
}
```

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/83eeee610b4d6696e10d2d27f1d07bdfee2269d3

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Windows, Nvidia 3090

**Comment by fire** [comment]
Currently we copy the uv data directly. Do you think it's good to do the 1-y transform?

**Comment by bqqbarbhg** [comment]
It's probably a good idea to do it for all extra UVs, can probably factor it into a utility function like `_flip_uv_y(Vector<Vector2> &p_uvs)` that modifies the coordinates.

**Comment by fire** [comment]
Yes.

```c++
void FBXDocument::_process_uv_set(PackedVector2Array &uv_array) {
	int uv_size = uv_array.size();
	for (int uv_i = 0; uv_i < uv_size; uv_i++) {
		Vector2 &uv = uv_array.write[uv_i];
		uv.y = 1.0 - uv.y;
	}
}
```

**Comment by bqqbarbhg** [comment]
And now if we want to add an option to disable the UV flipping at some point there's one centralized place to handle it.

**Comment by fire** [comment]
Added in https://github.com/V-Sekai/godot-ufbx/commit/8e355ff8f5d3c5e68ed87bdb56c5cb3b4878fd75
