### ISSUE TITLE
Non-inherited scale is broken

### ISSUE THREAD

**Issue by bqqbarbhg** [V-Sekai/godot-ufbx#28]
### Issue description

Nodes using `UFBX_INHERIT_NO_SCALE` do not behave correctly as the Godot scene graph does not support this mode. This is nearly impossible to simulate in the generic case. Fortunately vast majority of the cases use uniform scaling which can be compensated for.

I think I will actually fix this on ufbx side so the workaround can be used in any importers using ufbx, but I'll leave this tracking issue here as it's not strictly a bug in ufbx (though there was one related to this, which cancelled out and made this not show up in practice for a while).

### Steps to reproduce

- Import https://sketchfab.com/3d-models/facial-body-animated-party-f-0001-actorcore-a676e4d13bea4ee6b6a2ba6201d5308b
- Use `UFBX_SPACE_CONVERSION_TRANSFORM_ROOT` (not exposed without modification)
- Note that all the bones have scale `0.01` (correct), but they shouldn't propagate

### Using a released version?

0291fa4

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Windows, Godot 4.2 master

**Comment by bqqbarbhg** [comment]
Relevant hack in FBX2gLTF: https://github.com/godotengine/FBX2glTF/blob/bc05f0f8a6ff15963b8c1637b505e382303b248e/src/fbx/Fbx2Raw.cpp#L668-L684

**Comment by fire** [comment]
Saw your issue, any idea how to resolve?

**Comment by bqqbarbhg** [comment]
Yeah I'm working on this on ufbx side, it'll take a short while as it's quite complex and I want to make sure to get it right.

**Comment by fire** [comment]
Should be fixed after https://github.com/V-Sekai/godot-ufbx/commit/b158d9f80a999a5e1ee73134458da6d6aba3af97 ?

**Comment by bqqbarbhg** [comment]
Yep should work fine now!
