### ISSUE TITLE
Restore pivots after global scaling

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#29]
### Describe the proposed feature and how it helps to overcome a problem or limitation

@bqqbarbhg A feature we wanted in fbx2gltf was to preserve the pivots from 3dmax etc.

### Other information about your context or usecase.

We have a 3d max bedroom and we want to import the scene correctly.

### If known, describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

???

### Anything else

Maybe this code is correct. We never got it to work perfectly https://github.com/godotengine/FBX2glTF/commit/b994b479706cfaa7a5af2d05da768d24adedc5e0 with animations.

**Comment by bqqbarbhg** [comment]
There is a lot of work in ufbx to handle 3ds Max pivots (geometric transforms) correctly, so it should work already without modification.

However, if you want to expose the geometric transforms to users that is doable with a single line change in `FBXDocument::_parse()`:

```diff
- opts.geometry_transform_handling = UFBX_GEOMETRY_TRANSFORM_HANDLING_MODIFY_GEOMETRY;
+ opts.geometry_transform_handling = UFBX_GEOMETRY_TRANSFORM_HANDLING_HELPER_NODES;
```

The existing `UFBX_GEOMETRY_TRANSFORM_HANDLING_MODIFY_GEOMETRY` tries to modify non-instanced mesh geometry when using 3ds Max pivots to hide them from users. However, in more complex cases it has to create virtual "helper" nodes that contain the extra non-inherited transform.

When using `UFBX_GEOMETRY_TRANSFORM_HANDLING_HELPER_NODES` ufbx will unconditionally create the helper nodes and won't touch the geometry itself.

Both of these methods have been tested on animated and skinned geometry so they should be quite robust, however if you find a case that breaks let me know and I'll take a look at it!

**Comment by fire** [comment]
I think the user request was to emulate pivots.

1. mesh is at object origin
2. node transforms are relative to the parents
3. it's unlikely all nodes are at the global origin

**Comment by fire** [comment]
To emulate pivots for compatibility with a different importer system.

**Comment by fire** [comment]
Closing for now.
