### ISSUE TITLE
Failing to import FBX exported from Marvelous Designer

### ISSUE THREAD

**Issue by bqqbarbhg** [V-Sekai/godot-ufbx#31]
### Issue description

Trying to import a test file exported from Marvelous designer fails with the following error stack:

```
modules\fbx\fbx_document.cpp:1381 - Condition "out_roots.size() == 0" is true. Returning: FAILED
modules\fbx\fbx_document.cpp:1459 - Condition "_verify_skin(p_state, skin)" is true. Returning: ERR_PARSE_ERROR
modules\fbx\fbx_document.cpp:3119 - Condition "err != OK" is true. Returning: ERR_PARSE_ERROR
modules\fbx\fbx_document.cpp:2973 - Condition "err != OK" is true. Returning: err
modules\fbx\fbx_document.cpp:3170 - Condition "err != OK" is true. Returning: err
```

The issue has something to do with skinning code, which is taken pretty straight from the glTF importer. There is something extremely cursed about skinned Marvelous files, as it connects skin clusters to root. However ufbx already has an internal quirk mode to fix it, but it's possibly related to the issue.

### Steps to reproduce

* Download https://ufbx-dataset.b-cdn.net/local/hana/hana.fbx (CC0)
* Try to import the file
* Note that it fails with the error mentioned

### Using a released version?

cd3932a

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Windows, Godot 4.2 master

**Comment by fire** [comment]
How does the internal quirks model to fix Hana work?

**Comment by bqqbarbhg** [comment]
The quirks mode is enabled by default and should stop it from parenting the skin clusters to the root, so that shouldn't be an issue.

However there is likely some other things that are off with the model which causes issued on the Godot importer side. I'll check if I can find something broken in the loaded ufbx scene tomorrow.

**Comment by bqqbarbhg** [comment]
Loads now as of 572fba3, but looks like UVs may be wrong?

![image](https://github.com/V-Sekai/godot-ufbx/assets/3875461/db002045-3926-4679-8b35-94071d8f9e80)

**Comment by bqqbarbhg** [comment]
Turns out it was using UDIM textures and even then the UVs were incorrect for parts of the mesh, so the importer is working as intended (without UDIM support that is).
