### ISSUE TITLE
Scale slider values for the Normal Map lost

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#33]
### Issue description

The shader material has scale slider for the Normal Map

### Steps to reproduce

Import a fbx with normal scaling.

### Minimal reproduction project (For SDK or engine issues)

@bqqbarbhg Do you know of a fbx with this property?

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/b3d55a43c63e5a306793af85dfd37e805a265dd4

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Windows

**Comment by bqqbarbhg** [comment]
It is possible in _some_ material models, but I don't remember if the standard FBX Phong supported it, really depends on the exporter.

**Comment by fire** [comment]
Will be moving to the godot pr for merging.
