### ISSUE TITLE
Importer versioning

### ISSUE THREAD

**Issue by bqqbarbhg** [V-Sekai/godot-ufbx#34]
### Describe the proposed feature and how it helps to overcome a problem or limitation

There should be some way of using the previous FBX2glTF path for older projects/assets. There will always be some subtle differences in ufbx/FBX2glTF. Especially as the imported scene graph may be depended deeply on by users any slight variation (node order, name, skeleton root, what have you), even when imperceptible when rendering, will cause compatibility issues.

These two Godot PRs might be relevant for how assets can be versioned:
* https://github.com/godotengine/godot/pull/84034
* https://github.com/godotengine/godot/pull/84271

Fortunately, maintaining the FBX2glTF path should not be too bothersome as it's an external application and the glTF path is kept up to date, being the preferred asset format for the engine.

It is unclear to me where this should be implemented, but just adding a tracking issue here for now.

### Other information about your context or usecase.

Having an existing project with FBX files, updating to use ufbx for FBX importing would potentially cause compatibility issues with existing imported assets, where reimports would subtly change the imported scene graph.

### If known, describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

Ideally there'd be per-asset or per-project metadata for which importer to use. 

### Anything else

\-

**Comment by fire** [comment]
Will be moving to the godot pr for merging.
